title: Yiheng Lin
description: Online Learning & Control | PhD Student at Caltech..

highlighter: rouge
date_format: "%b %-d, %Y"

github_username: yihenglin97
twitter_username: LinYiheng
facebook_username: YihengLin97
scholar_userid: S1wSEggAAAAJ
